# docker-compose.yml

version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

  nodeserver:
    depends_on:
      - db
    build:
      context: ./node
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; node index.js'
    container_name: nodeserver
    tty: true
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    # ports:
    #   - "3000:3000" # Uncomment this line if you want to expose the port
    networks:
      - app-network

  nginx:
    depends_on:
      - nodeserver
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
